name: simple_form_field_validator
description: Helper class to implement FormFieldValidator
version: 1.0.0
repository: https://github.com/hpoul/flutter_utils
homepage: https://github.com/hpoul/flutter_utils/tree/master/packages/simple_form_field_validator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

